<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="FIN-IT-LT-236" failures="4" tests="7" name="LoginTest" time="42.486" errors="0" timestamp="2025-02-14T15:42:54 IST">
  <testcase classname="testCase.TC003_LoginDDT" name="verify_loginDDT" time="5.214"/>
  <testcase classname="testCase.TC003_LoginDDT" name="verify_loginDDT" time="1.592">
    <failure type="java.lang.AssertionError" message="Login succeeded for invalid credentials. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login succeeded for invalid credentials. expected [true] but found [false]
at testCase.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCase.TC003_LoginDDT" name="verify_loginDDT" time="4.107">
    <failure type="java.lang.AssertionError" message="Exception occurred during test execution.">
      <![CDATA[java.lang.AssertionError: Exception occurred during test execution.
at testCase.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCase.TC003_LoginDDT" name="verify_loginDDT" time="3.889">
    <failure type="java.lang.AssertionError" message="Exception occurred during test execution.">
      <![CDATA[java.lang.AssertionError: Exception occurred during test execution.
at testCase.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCase.TC003_LoginDDT" name="verify_loginDDT" time="4.434"/>
  <testcase classname="testCase.TC002_Login_page" name="verify_login" time="1.4"/>
  <testcase classname="testCase.TC001_Account_Reg" name="verify_acount_reg" time="0.72">
    <failure type="java.lang.Error" message="Unresolved compilation problems: 
	RandomStringUtils cannot be resolved
	RandomStringUtils cannot be resolved
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
RandomStringUtils cannot be resolved
RandomStringUtils cannot be resolved

at testBase.BaseClass.randAlphaNumeric(BaseClass.java:152)
at testCase.TC001_Account_Reg.verify_acount_reg(TC001_Account_Reg.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_acount_reg -->
</testsuite> <!-- LoginTest -->
